import {courses,sentences} from './data.js';
import {normalize,assess,schedule,restore} from './engine.js';
import {structures,wordInfo,dictionary} from './analysis-data.js';
import {compareSpeech} from './speech-score.js';
import {safeSettings,validSession} from './preferences.js';
import {filterCourses,searchSentences,courseSummary} from './catalog.js';
import {learningUnits,learningLessons} from './grammar-data.js';
import {gradeExercise,lessonExercises} from './grammar-engine.js';
import {learningPathModel,lessonStageLabel} from './grammar-view.js';
import {grammarTagsForSentence} from './grammar-links.js';
import {createSoundEngine,SOUND_PROFILES} from './sound-engine.js';
import {AUDIO_SAMPLE_RATE,isRecordingLongEnough} from './audio-policy.js';
const $=s=>document.querySelector(s),KEY='first-steps-v2';
const defaults={theme:'dark',immersive:false,voice:'am_michael',rate:1,loops:2,successLoops:1,sound:true,soundProfile:'wood',soundVolume:90,loudKeysV1:true,fragment:false,autoNext:false,font:'sans',size:38,inputStyle:'line',revealAt:3,phonetics:true,chinese:true,preview:true,compact:false,shortcuts:true,spectrum:true,goal:10,keys:{play:'p',answer:'a',favorite:'s',next:'ArrowRight',previous:'ArrowLeft'}};
let data=restore(null),settings=structuredClone(defaults),wordFavorites=[],saved=null;
try{const x=JSON.parse(localStorage.getItem(KEY));if(x){data=restore(JSON.stringify(x.data));settings=safeSettings(x.settings,defaults);if(x.settings?.loudKeysV1!==true){settings.soundVolume=Math.max(settings.soundVolume,90);settings.loudKeysV1=true;}wordFavorites=Array.isArray(x.wordFavorites)?x.wordFavorites.filter(w=>typeof w==='string'&&dictionary[w]):[];saved=validSession(x.session,sentences.map(s=>s.id),['dictation','puzzle','learn','speak'])?x.session:null;}}catch{}
const modes={dictation:'听写',puzzle:'拼图',learn:'学习',speak:'口语'},voiceNames={am_michael:'美式男声',af_heart:'美式女声',bf_emma:'英式女声',bm_george:'英式男声'};
let session={ids:courses[0].items.map(s=>s.id),index:0,mode:'speak',elapsed:0},page='courses',panel=false,analysisView='words',q={},dialogAction=null,playToken=0,player=null,mic=null,rec=null,recordUrl=null,recordTimer=null,recordStart=0,requesting=false,autoTimer=null,ac=null,analyser=null,micGraph=null,modelInfo={tts:'加载中',asr:'加载中'};
let selectedCourseId=null,catalogLimit=18,selectedLessonId=null,lessonSession=null;
const feedback=createSoundEngine({getProfile:()=>settings.soundProfile,getVolume:()=>settings.soundVolume});
const catalogFilters={query:'',category:'全部',series:'全部',level:'全部'};
const paths={exit:'M9 4H4v16h5m4-13 5 5-5 5m-5-5h10',sound:'m11 4-6 5H2v6h3l6 5V4m4 4a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12m7 0a3 3 0 1 0 6 0 3 3 0 0 0-6 0',star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z',next:'m9 5 7 7-7 7',prev:'m15 5-7 7 7 7',gear:'M4 7h16M4 17h16M8 4v6m8 4v6',full:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0V5m-4 5v2a7 7 0 0 0 14 0v-2m-7 9v3m-4 0h8',check:'m5 12 4 4L20 5',undo:'M8 4 3 9l5 5M3 9h11a6 6 0 0 1 0 12',clear:'m6 6 12 12M6 18 18 6',book:'M12 6c-4-3-8-3-10-2v15c4-1 7-1 10 2m0-15c4-3 8-3 10-2v15c-4-1-7-1-10 2V6',grid:'M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z'};
const ic=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.book}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,cls='',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const iconButton=(n,action,label,attrs='')=>button(ic(n),action,'icon',`title="${label}" aria-label="${label}" ${attrs}`);
const current=()=>sentences.find(s=>s.id===session.ids[session.index]);
const today=()=>new Date().toLocaleDateString('en-CA');
const due=()=>sentences.filter(s=>data.records[s.id]?.due<=Date.now());
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:2,data,settings,wordFavorites,session:page==='practice'?{...session}:saved}));}catch{toast('无法保存，请导出备份。');}}
function toast(t){$('#toast').textContent=t;$('#toast').className='show';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').className='',4000);}
function stopSpeech(){playToken++;if(player){player.pause();player=null;}speechSynthesis?.cancel();}
function cleanup(){stopSpeech();clearTimeout(autoTimer);clearTimeout(recordTimer);if(rec?.state==='recording')rec.stop();mic?.getTracks().forEach(t=>t.stop());mic=null;micGraph?.disconnect();micGraph=null;if(recordUrl){URL.revokeObjectURL(recordUrl);recordUrl=null;}}
function shuffled(a){return a.map(v=>[Math.random(),v]).sort((x,y)=>x[0]-y[0]).map(x=>x[1]);}
function reset(){cleanup();q={id:crypto.randomUUID(),inputs:[],chosen:[],completedWords:[],errors:0,checked:false,revealed:false,result:null,recordState:'idle',hideEnglish:false,phase:settings.fragment&&session.mode==='dictation'&&current()?.id?.startsWith('u')?'chunks':'sentence'};const s=current();q.pool=shuffled((q.phase==='chunks'?structures[s.id].map(x=>x[1]):s.en.split(' ')).map((text,i)=>({text,i})));}
function start(ids,mode='dictation',index=0,elapsed=0){ids=ids.filter(id=>sentences.some(s=>s.id===id));if(!ids.length)return toast('还没有需要练习的内容。');session={ids,mode,index:Math.min(index,ids.length-1),elapsed};page='practice';panel=false;reset();saved={...session};save();render();window.scrollTo(0,0);autoPlay();}
function applyTheme(){document.documentElement.dataset.theme=settings.theme;document.documentElement.style.setProperty('--answer-size',settings.size+'px');document.documentElement.style.setProperty('--answer-font',({sans:'Arial, sans-serif',round:'Arial Rounded MT Bold, sans-serif',serif:'Georgia, serif',mono:'Menlo, monospace'})[settings.font]||'Arial');}
function fmt(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function grammar(){const s=current(),tags=grammarTagsForSentence(s).map(id=>learningLessons.find(lesson=>lesson.id===id)).filter(Boolean);const groups=analysisView==='grammar'?structures[s.id].map(([role,text],i)=>`<div class="grammar-group" style="--group:${['#55b7ed','#6bcd8c','#ead557','#d989bc','#ab97e5'][i%5]}"><span class="role">${role}</span><div class="group-line">${text.split(' ').map(w=>button(esc(w),'word','big-word',`data-word="${esc(w)}"`)).join(' ')}</div>${settings.phonetics?`<small>${text.split(' ').map(w=>wordInfo(w).ipa?'/'+wordInfo(w).ipa+'/':'—').join(' ')}</small>`:''}<p>${text.split(' ').map(w=>wordInfo(w).meaning).join(' / ')}</p></div>`).join(''):s.en.split(' ').map(w=>{const d=wordInfo(w);return `<div class="word-column"><span>${d.meaning}</span>${settings.phonetics&&d.ipa?`<small>/${d.ipa}/</small>`:''}${button(esc(w),'word','big-word',`data-word="${esc(w)}"`)}<em>${d.pos}</em></div>`;}).join('');return `<div class="analysis-switch">${button(analysisView==='words'?'查看句子成分':'查看单词信息','analysis','small-outline')}</div><div class="analysis-words ${analysisView}">${groups}</div><div class="sentence-grammar-links"><span>这句话正在用</span>${tags.map(lesson=>button(esc(lesson.title),'grammar-start','grammar-chip',`data-id="${lesson.id}"`)).join('')}</div>`;}
function settingsPanel(){const item=(title,control)=>`<label><span>${title}</span>${control}</label>`, select=(key,opts)=>`<select data-setting="${key}">${opts.map(([v,t])=>`<option value="${v}" ${String(settings[key])===String(v)?'selected':''}>${t}</option>`).join('')}</select>`, toggle=(key)=>`<input type="checkbox" role="switch" data-setting="${key}" ${settings[key]?'checked':''}>`;
return `<aside class="settings-popover" aria-label="练习设置"><div class="panel-title"><h2>练习设置</h2>${iconButton('clear','settings','关闭设置')}</div><div class="setting-grid">${item('显示风格',select('theme',[['dark','深色'],['light','浅色']]))}${item('沉浸界面',toggle('immersive'))}${item('发音偏好',select('voice',Object.entries(voiceNames)))}${item('语速',select('rate',[[0.6,'0.6 ×'],[0.8,'0.8 ×'],[1,'1.0 ×'],[1.2,'1.2 ×']]))}${item('拼写声音',select('soundProfile',Object.entries(SOUND_PROFILES).map(([key,value])=>[key,value.label])))}${item('音效音量',`<input aria-label="音效音量" type="range" min="0" max="100" data-setting="soundVolume" value="${settings.soundVolume}">`)}${item('进入后播放',select('loops',[[0,'不自动播放'],[1,'1 次'],[2,'2 次'],[3,'3 次']]))}${item('答对后播放',select('successLoops',[[0,'不播放'],[1,'1 次'],[2,'2 次'],[3,'3 次']]))}${item('分段拼接 → 听写',toggle('fragment'))}${item('自动下一句',toggle('autoNext'))}${item('错误后提示',select('revealAt',[[1,'1 次'],[2,'2 次'],[3,'3 次'],[0,'不自动提示']]))}${item('显示音标',toggle('phonetics'))}${item('显示中文',toggle('chinese'))}${item('下一句预览',toggle('preview'))}${item('紧凑工具栏',toggle('compact'))}${item('声音频谱',toggle('spectrum'))}${item('快捷键提示',toggle('shortcuts'))}${item('输入字体',select('font',[['sans','无衬线'],['round','圆体'],['serif','衬线'],['mono','等宽']]))}${item('输入框样式',select('inputStyle',[['line','横线'],['box','方框']]))}${item('输入字号',`<input aria-label="输入字号" type="range" min="24" max="56" data-setting="size" value="${settings.size}">`)}</div><div class="model-card"><strong>本机语音模型</strong><p>Kokoro 82M · ${modelInfo.tts}<br>Whisper tiny.en · ${modelInfo.asr}</p>${button('试听所选声音','play','small-outline')}${button('试听拼写声音','sound-preview','small-outline')}${button('自定义快捷键','shortcuts','small-outline')}</div></aside>`;}
function render(){applyTheme();if(page!=='practice')return renderLibrary();const s=current(),course=courses.find(c=>c.id===s.course),show=q.checked||q.revealed||session.mode==='learn',speaking=session.mode==='speak',position=course.items.findIndex(x=>x.id===s.id),previous=position>0?course.items[position-1]:null;
$('#app').innerHTML=`<div class="practice ${settings.immersive?'immersive':''} ${show?'answer-visible':''}"><div class="progress-line"><i style="width:${(session.index+(q.checked?1:0))/session.ids.length*100}%"></i></div><header class="practice-header"><div class="breadcrumb">${iconButton('exit','library','退出练习')}<span>初言 · 零基础生活英语</span><b>›</b><strong>${course.title}</strong></div><div class="header-tools"><select aria-label="练习模式" id="mode">${Object.entries(modes).map(([v,t])=>`<option value="${v}" ${session.mode===v?'selected':''}>${t}</option>`).join('')}</select><span class="timer" id="timer">${fmt(session.elapsed)}</span><span class="counter">${session.index+(q.checked?1:0)} <em>/ ${session.ids.length}</em></span>${iconButton('full','fullscreen','全屏')}${iconButton('gear','settings','练习设置')}</div></header>${panel?settingsPanel():''}<main class="practice-body ${speaking?'speaking':''}">${speaking?`${previous&&s.speaker?`<div class="dialogue-context"><span>上一句 · ${esc(previous.speaker||'对话')}</span><p>${esc(previous.en)}</p><small>${esc(previous.zh)}</small>${button(ic('sound')+' 听上一句','context-play','text-button',`data-id="${previous.id}"`)}</div>`:''}<span class="dialogue-role">${esc(s.speaker||course.title)}</span><h1 class="speaking-text ${q.hideEnglish?'prompt-hidden':''}">${q.hideEnglish?'看中文，说出英文':esc(s.en)}</h1>${settings.chinese||q.hideEnglish?`<p class="speaking-translation">${esc(s.zh)}</p>`:''}<div class="speaking-actions">${button(q.hideEnglish?'显示英文':'遮住英文 · 中文开口','toggle-speaking-prompt','small-outline')}${button('跟读完成（自评）','self-complete','small-outline')}</div>`:`${settings.chinese?`<h1 class="translation">${esc(s.zh)}</h1>`:'<h1 class="translation muted">听声音，写出你听到的句子</h1>'}${show?grammar():session.mode==='puzzle'||q.phase==='chunks'?`<div class="puzzle-answer"><div class="chosen-words">${q.chosen.length?q.chosen.map(i=>button(esc(q.pool.find(p=>p.i===i).text),'unpick','word-token',`data-index="${i}"`)).join(''):'<span>按顺序点选词块，组成完整句子</span>'}</div><div class="puzzle-tools">${iconButton('undo','undo','撤销上一个词',!q.chosen.length?'disabled':'')}${iconButton('clear','clear','清空词块',!q.chosen.length?'disabled':'')}</div></div><div class="puzzle-pool">${q.pool.map(p=>button(esc(p.text),'pick','word-token',`data-index="${p.i}" ${q.chosen.includes(p.i)?'disabled':''}`)).join('')}</div>${q.phase==='chunks'?'<p class="helper">先完成句子成分拼接，再进行逐词听写。</p>':''}`:`<div class="inputs ${settings.inputStyle}">${s.en.split(' ').map((w,i)=>`<input type="text" aria-label="第 ${i+1} 个单词" data-index="${i}" data-input="word" value="${esc(q.inputs[i]||'')}" style="width:${Math.max(62,normalize(w).length*(settings.size*.58)+18)}px" autocomplete="off" autocapitalize="off" spellcheck="false" class="${q.errors?'has-error':''}">`).join('')}</div><div class="input-hint">输入完成自动检查 · 空格跳到下一词 · ${button('检查答案 ↵','check','text-button')}</div>`}`}
${q.message?`<div class="answer-feedback ${q.checked?'good':''}" role="status">${q.message}</div>`:''}
${show&&!speaking?`<div class="inline-speech">${button(ic('mic')+' 口语练习 · 空格开始','record','speech-pill')}</div>`:''}
${show&&!speaking?`<div class="grammar-notes"><span>${s.en.endsWith('?')?'疑问句':'常用表达'}</span><span>${esc(s.note||'结合场景练习完整表达。')}</span></div>`:''}
${speaking?`<div class="mic-zone">${button(q.recordState==='recording'?'■':ic('mic'),'record','main-mic '+(q.recordState==='recording'?'recording':''),`aria-label="${q.recordState==='recording'?'停止录音':'开始口语录音'}" ${q.recordState==='processing'?'disabled':''}`)}<p id="record-label">${q.recordState==='recording'?'正在录音 · 再按空格停止':q.recordState==='processing'?'本地语音模型正在识别…':'点击或按空格开始'}</p><small>声音仅发送到本机模型进行识别</small></div>`:''}
${q.result?renderSpeechResult():''}
${show&&settings.preview&&session.index<session.ids.length-1?`<div class="next-preview"><span>接下来 ${session.index+2}/${session.ids.length}</span>${esc(sentences.find(x=>x.id===session.ids[session.index+1]).zh)} ${button('↵','next','next-key')}</div>`:''}
${show?`<div class="review-actions">${button('再练一次','retry','text-button')}${session.mode==='learn'&&!q.checked?button('记住了，下一句','learn-next','text-button'):''}</div>`:''}
</main><canvas class="spectrum" id="spectrum" width="600" height="32" aria-hidden="true"></canvas><footer class="toolbar ${settings.compact?'compact':''}">${iconButton('prev','prev','上一句',session.index===0?'disabled':'')}${iconButton('sound','play','朗读原句')}${!['speak','learn'].includes(session.mode)?iconButton('eye','reveal',q.checked?'查看句子提示':'查看 / 隐藏答案'):''}${iconButton('star','favorite',data.favorites.includes(s.id)?'取消收藏':'收藏句子',`aria-pressed="${data.favorites.includes(s.id)}"`)}${iconButton('next','next',session.index===session.ids.length-1?'完成练习':'下一句')}</footer><div id="shortcut-overlay" class="shortcut-overlay" hidden></div></div>`;
if(q.recordState==='recording'&&!speaking){const b=document.querySelector('[data-action="record"]');if(b)b.textContent='停止录音 · 空格';}
if(q.result&&recordUrl){const a=$('#record-audio');if(a)a.src=recordUrl;}
}
function renderSpeechResult(){const r=q.result;return `<section class="speech-result"><div class="result-header"><div><strong>${r.agreement}%</strong><span>识别一致度</span></div><div><strong>${r.coverage}%</strong><span>原句词语覆盖</span></div><div><strong>${r.seconds.toFixed(1)}s</strong><span>录音时长</span></div></div><p>识别内容：${esc(r.text||'没有识别到清晰语音')}</p><div class="result-words">${r.words.map(w=>`<span class="${w.status}" title="${esc(w.status==='match'?'识别相符':w.status==='missing'?'未识别到':w.status==='extra'?'额外识别词':'识别为 '+w.heard)}">${esc(w.expected||'+'+w.heard)}${w.status==='changed'?`<small>→ ${esc(w.heard)}</small>`:''}</span>`).join('')}</div><audio id="record-audio" controls aria-label="回放我的录音"></audio><small>一致度按识别文字计算，不能代替音素发音评分。噪音、口音和模型识别误差会影响结果。</small>${button('重录一次','record','small-outline')}</section>`;}
function recordResult(ok){if(q.checked)return;data.records[current().id]=schedule(data.records[current().id],ok);data.daily[today()]=(data.daily[today()]||0)+1;q.checked=ok;save();}
function check(){if(q.checked)return;const s=current();const isPuzzle=session.mode==='puzzle'||q.phase==='chunks',answer=isPuzzle?q.chosen.map(i=>q.pool.find(p=>p.i===i).text).join(' '):q.inputs.join(' ');if(!answer.trim())return;
if(assess(answer,s.en)){if(q.phase==='chunks'){q.phase='sentence';q.chosen=[];q.inputs=[];q.message='词块拼接完成。现在听一遍，写出完整句子。';keySound('word');render();autoPlay();return;}recordResult(!q.revealed);q.checked=true;q.message=q.revealed?'已完成辅助练习，已安排复习。':'回答正确';keySound('success');render();const expected=q.id;play(s.en,settings.successLoops).finally(()=>{if(settings.autoNext&&q.id===expected)autoTimer=setTimeout(()=>next(1),700);});}
else{q.errors++;q.message=`还差一点，检查词序和拼写。第 ${q.errors} 次尝试`;keySound('error');if(q.errors===1)recordResult(false);if(settings.revealAt&&q.errors>=settings.revealAt){q.revealed=true;q.message='先对照答案理解，再点“再练一次”巩固。';}render();}}
function next(direction){if(direction<0&&session.index===0)return;if(direction>0&&session.mode==='learn'&&!q.checked)recordResult(true);if(direction>0&&session.index===session.ids.length-1){cleanup();saved=null;page='complete';save();renderLibrary();return;}session.index=Math.max(0,Math.min(session.ids.length-1,session.index+direction));reset();saved={...session};save();render();autoPlay();}
function autoPlay(){clearTimeout(autoTimer);if(!settings.loops)return;const id=q.id;autoTimer=setTimeout(()=>{if(id===q.id&&page==='practice')play(current().en,settings.loops);},300);}
async function play(text=current().en,loops=1){if(!loops)return;stopSpeech();const token=playToken,voice=settings.voice,speed=settings.rate;try{const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice,speed})});if(!r.ok)throw Error();const blob=await r.blob();if(token!==playToken)return;const url=URL.createObjectURL(blob);try{for(let i=0;i<loops&&token===playToken;i++){player=new Audio(url);setupAnalyser(player);await new Promise((resolve,reject)=>{player.onended=resolve;player.onpause=resolve;player.onerror=reject;player.play().catch(reject);});}}finally{URL.revokeObjectURL(url);}}catch{if(token===playToken)toast('模型朗读暂不可用。请检查服务窗口，或等待模型加载后再点朗读。');}}
function setupAnalyser(audio){try{ac??=new AudioContext();ac.resume();const source=ac.createMediaElementSource(audio);analyser=ac.createAnalyser();analyser.fftSize=128;source.connect(analyser);analyser.connect(ac.destination);}catch{}}
function draw(){const canvas=$('#spectrum');if(canvas){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,600,32);if(settings.spectrum&&analyser){const bins=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(bins);ctx.fillStyle='#69dce6';for(let i=0;i<bins.length;i++)ctx.fillRect(i*9+1,32-bins[i]/8,4,bins[i]/8);}}requestAnimationFrame(draw);}
function keySound(event='key',key='a'){feedback.play(event,key);}
async function record(){if(requesting||q.recordState==='processing')return;if(rec?.state==='recording'){rec.stop();return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return toast('此浏览器未提供录音能力，请在 Chrome 的 localhost 页面使用。');stopSpeech();const id=q.id;requesting=true;try{const acquired=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,channelCount:1}});if(q.id!==id||page!=='practice'){acquired.getTracks().forEach(t=>t.stop());return;}mic=acquired;ac??=new AudioContext();micGraph=ac.createMediaStreamSource(mic);analyser=ac.createAnalyser();analyser.fftSize=128;micGraph.connect(analyser);const chunks=[];rec=new MediaRecorder(mic);const recorder=rec;recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{acquired.getTracks().forEach(t=>t.stop());clearTimeout(recordTimer);micGraph?.disconnect();micGraph=null;if(q.id!==id||page!=='practice')return;q.recordState='processing';render();const blob=new Blob(chunks,{type:recorder.mimeType});if(recordUrl)URL.revokeObjectURL(recordUrl);recordUrl=URL.createObjectURL(blob);try{const decoded=await ac.decodeAudioData(await blob.arrayBuffer()),offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*AUDIO_SAMPLE_RATE),AUDIO_SAMPLE_RATE),src=offline.createBufferSource();src.buffer=decoded;src.connect(offline.destination);src.start();const samples=(await offline.startRendering()).getChannelData(0);if(!isRecordingLongEnough(samples.length))throw Error('录音太短，请说完整句子后再停止。');const response=await fetch('/api/asr',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:samples.buffer});const result=await response.json().catch(()=>({}));if(!response.ok)throw Error(result.error||'识别服务暂不可用，请稍后重试。');if(id!==q.id)return;q.result={...compareSpeech(current().en,result.text),text:result.text,seconds:decoded.duration,chunks:result.chunks};if(result.text.trim())recordResult(q.result.agreement>=80);else toast('没有识别到清晰语音，请靠近麦克风再试一次。');}catch(e){toast(e.message);}finally{if(q.id===id){q.recordState='idle';render();}}};recorder.start();recordStart=performance.now();q.recordState='recording';render();recordTimer=setTimeout(()=>{if(recorder.state==='recording')recorder.stop();},60000);}catch(e){const reason=e?.name==='NotFoundError'?'没有检测到麦克风，请连接耳机或 USB 麦克风后重试。':e?.name==='NotAllowedError'?'麦克风权限未开启，请允许 Chrome 和当前网站录音。':'无法使用麦克风，请检查输入设备后重试。';toast(reason);}finally{requesting=false;}}
function showDialog(title,html,action){$('#modal')?.remove();const d=document.createElement('dialog');d.id='modal';d.innerHTML=`<form method="dialog"><div class="panel-title"><h2>${title}</h2><button aria-label="关闭">${ic('clear')}</button></div>${html}</form>`;document.body.append(d);dialogAction=action;d.addEventListener('close',()=>d.remove());d.showModal();}
function toggleAnswer(){if(q.checked||session.mode==='learn'){const s=current();showDialog('句子提示',`<h3>${esc(s.en)}</h3><p>${esc(s.zh)}</p><p>${esc(s.note)}</p>`);}else{q.revealed=!q.revealed;render();}}
function wordDialog(word){const d=wordInfo(word),key=normalize(word);showDialog(word,`<p>${d.ipa?'/'+d.ipa+'/':''} · ${d.pos}</p><h3>${d.meaning}</h3><div class="dialog-actions">${button(ic('sound')+' 朗读','word-play','small-outline',`data-word="${esc(word)}"`)}${button(wordFavorites.includes(key)?'取消单词收藏':'收藏单词','word-favorite','small-outline',`data-word="${esc(key)}"`)}</div><p>例句：${esc(current().en)}</p>`);}
function sourceHTML(course){const s=course.source||{};return `<div class="source-line"><span>${esc(course.series||'课程')}</span><b>${esc(s.title||'初言课程')}</b><small>${esc(s.license||'')}</small>${String(s.url||'').startsWith('https://')?`<a href="${esc(s.url)}" target="_blank" rel="noreferrer">查看教材来源</a>`:''}${String(s.licenseUrl||'').startsWith('https://')?`<a href="${esc(s.licenseUrl)}" target="_blank" rel="noreferrer">查看许可</a>`:''}</div>`;}
function sentenceSourceHTML(s){if(!s.attribution)return '';const links=[String(s.sourceUrl||'').startsWith('https://')?`<a href="${esc(s.sourceUrl)}" target="_blank" rel="noreferrer">英文原句</a>`:'',String(s.translationUrl||'').startsWith('https://')?`<a href="${esc(s.translationUrl)}" target="_blank" rel="noreferrer">原中文句对</a>`:''].filter(Boolean).join(' · ');return `<details><summary>逐句来源与署名</summary><p>${esc(s.attribution)}</p>${links?`<p>${links}</p>`:''}${s.translationEdited?'<p><em>中文已按现代生活口语场景校订；英文原句保持来源文本。</em></p>':''}</details>`;}
function catalogPage(){
 const totals=courseSummary(courses),filtered=filterCourses(courses,catalogFilters),hits=searchSentences(courses,catalogFilters);
 const categories=['全部',...new Set(courses.map(c=>c.category))],series=['全部',...new Set(courses.map(c=>c.series))],levels=['全部','入门','基础','进阶'];
 const opts=(values,value)=>values.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('');
 const cards=filtered.slice(0,catalogLimit).map((c,i)=>`<article class="course-card"><div class="course-meta"><span>${esc(c.series)}</span><small>${esc(c.level)} · ${esc(c.category)}</small></div><h2>${esc(c.title)}</h2><p>${esc(c.subtitle)}</p><small>${c.items.filter(x=>data.records[x.id]?.correct>0).length} / ${c.items.length} 已练习</small><div class="course-actions">${button(ic('mic')+' 开口练习','course','accent',`data-id="${esc(c.id)}" data-mode="speak"`)}${button('查看 '+c.items.length+' 句','course-details','small-outline',`data-id="${esc(c.id)}"`)}${button('学习','course','small-outline',`data-id="${esc(c.id)}" data-mode="learn"`)}${button('听写','course','small-outline',`data-id="${esc(c.id)}" data-mode="dictation"`)}${button('拼图','course','small-outline',`data-id="${esc(c.id)}" data-mode="puzzle"`)}</div></article>`).join('');
 const rows=hits.slice(0,60).map(({course,sentence,index})=>`<article class="sentence-row search-hit"><div><small>${esc(course.title)} · 第 ${index+1} 句</small><h3>${esc(sentence.en)}</h3><p>${esc(sentence.zh)}</p></div>${button(ic('sound'),'sentence-play','icon',`data-id="${esc(sentence.id)}" aria-label="朗读句子"`)}${button('练口语','sentence-start','small-outline',`data-course="${esc(course.id)}" data-index="${index}"`)}</article>`).join('');
 return `<div class="library-heading catalog-heading"><div><h1>日常英语口语课程</h1><p>${totals.courses} 课 · ${totals.sentences} 个可开口练习的句子 · 全部保存在本机</p></div><div class="catalog-count"><strong>${totals.sentences}</strong><span>口语句子</span></div></div>${saved?`<div class="resume-band"><span>上次练到第 ${saved.index+1} 句 · ${modes[saved.mode]}</span>${button('继续练习','resume','accent')}</div>`:''}<section class="catalog-tools"><label>搜索课程或句子<input id="course-search" value="${esc(catalogFilters.query)}" placeholder="例如：点咖啡、机场、Could you…"></label><label>教材来源<select data-catalog="series">${opts(series,catalogFilters.series)}</select></label><label>学习难度<select data-catalog="level">${opts(levels,catalogFilters.level)}</select></label><div class="category-filter">${categories.map(v=>button(v,'category',v===catalogFilters.category?'active':'',`data-value="${esc(v)}"`)).join('')}</div></section>${catalogFilters.query&&hits.length?`<section class="search-results"><h2>找到 ${hits.length} 个相关句子</h2>${rows}${hits.length>60?`<p>只显示前 60 条，请输入更具体的场景。</p>`:''}</section>`:''}<div class="catalog-summary"><h2>${catalogFilters.query?'相关课程':'全部课程'}</h2><span>${filtered.length} 课</span></div><div class="course-grid">${cards||'<div class="empty">没有找到符合条件的课程，请减少筛选条件。</div>'}</div>${filtered.length>catalogLimit?button(`继续显示（还有 ${filtered.length-catalogLimit} 课）`,'more-courses','load-more'):''}`;
}
function coursePage(){
 const c=courses.find(x=>x.id===selectedCourseId);if(!c)return catalogPage();
 const items=c.items.map((s,i)=>`<article class="lesson-sentence"><span>${String(i+1).padStart(2,'0')}</span><div>${s.speaker?`<small>${esc(s.speaker)}</small>`:''}<h3>${esc(s.en)}</h3><p>${esc(s.zh)}</p>${c.series==='日常口语精选'?'':`<em>${esc(s.note||'')}</em>`}${sentenceSourceHTML(s)}</div>${button(ic('sound'),'sentence-play','icon',`data-id="${esc(s.id)}" aria-label="朗读第 ${i+1} 句"`)}${button('从这里练口语','sentence-start','small-outline',`data-course="${esc(c.id)}" data-index="${i}"`)}</article>`).join('');
 return `${button('← 返回全部课程','back-courses','text-button')}<div class="course-title"><span>${esc(c.series)} · ${esc(c.level)} · ${esc(c.category)}</span><h1>${esc(c.title)}</h1><p>${esc(c.subtitle)}</p>${c.tip?`<p class="course-tip">${esc(c.tip)}</p>`:''}<div class="dialog-actions">${button(ic('mic')+' 整课口语练习','course','accent',`data-id="${esc(c.id)}" data-mode="speak"`)}${button('整课学习','course','small-outline',`data-id="${esc(c.id)}" data-mode="learn"`)}${button('整课听写','course','small-outline',`data-id="${esc(c.id)}" data-mode="dictation"`)}</div></div>${sourceHTML(c)}<div class="lesson-list">${items}</div>`;
}
function learningPathPage(){
 const model=learningPathModel(data.grammarProgress),next=learningLessons.find(lesson=>lesson.id===model.nextLessonId);
 const units=model.units.map((unit,index)=>{const lessons=unit.lessons.map((lesson,lessonIndex)=>{const done=data.grammarProgress[lesson.id]?.completed;return `<button class="path-lesson ${done?'done':''}" data-action="grammar-start" data-id="${lesson.id}"><span>${String(lessonIndex+1).padStart(2,'0')}</span><div><b>${esc(lesson.title)}</b><small>${esc(lesson.focus)} · 约 6–10 分钟</small></div><em>${done?'✓ 已掌握':'开始'}</em></button>`;}).join('');return `<details class="path-unit" ${index===0||unit.completed>0&&unit.completed<unit.total?'open':''}><summary><span class="unit-number">${String(unit.order).padStart(2,'0')}</span><div><b>${esc(unit.title)}</b><small>${esc(unit.subtitle)}</small></div><strong>${unit.completed}/${unit.total}</strong></summary><div class="unit-progress"><i style="width:${unit.percent}%"></i></div><div class="path-lessons">${lessons}</div></details>`;}).join('');
 return `<section class="path-hero"><div><span>从字母音到自然开口</span><h1>自然拼读＋邪修语法闯关</h1><p>不先背术语。听声音、搭骨架、抓错句，再把英语说出口。</p><div class="dialog-actions">${next?button(`继续：${esc(next.title)}`,'grammar-start','accent',`data-id="${next.id}"`):''}${button('试听拼写手感','sound-preview','small-outline')}</div></div><div class="path-score"><strong>${model.percent}%</strong><span>${model.completedLessons} / ${model.totalLessons} 微课</span><label>拼写声音<select data-setting="soundProfile">${Object.entries(SOUND_PROFILES).map(([key,value])=>`<option value="${key}" ${settings.soundProfile===key?'selected':''}>${value.label}</option>`).join('')}</select></label></div></section><div class="path-intro"><b>学习顺序</b><span>一句人话</span><span>场景开门</span><span>搭骨架</span><span>变形术</span><span>抓虫找茬</span><span>张嘴就说</span></div><div class="learning-path">${units}</div>`;
}
function resetGrammarStage(){const exercise=currentGrammarExercise();lessonSession.chosen=[];lessonSession.input='';lessonSession.checked=false;lessonSession.correct=false;lessonSession.revealed=false;lessonSession.pool=exercise?.mode==='build'?shuffled(exercise.tokens.map((text,index)=>({text,index}))):[];}
function startGrammarLesson(id){const lesson=learningLessons.find(item=>item.id===id);if(!lesson)return;if(page==='practice')saved={...session};cleanup();selectedLessonId=id;lessonSession={lessonId:id,index:0,score:0,attempts:0,done:false,chosen:[],input:'',checked:false,correct:false,revealed:false,pool:[]};resetGrammarStage();page='grammar-lesson';save();renderLibrary();window.scrollTo(0,0);}
function currentGrammarLesson(){return learningLessons.find(item=>item.id===selectedLessonId);}
function currentGrammarExercise(){return lessonExercises(selectedLessonId)[lessonSession?.index||0];}
function completeGrammarAnswer(value,force=false){const exercise=currentGrammarExercise();if(!exercise||lessonSession.checked)return;const correct=force||gradeExercise(value,exercise.answer);lessonSession.attempts++;lessonSession.checked=true;lessonSession.correct=correct;if(correct){lessonSession.score++;feedback.play(exercise.mode==='build'?'word':'success');}else{feedback.play('error');const old=data.grammarMistakes[exercise.id]||{lessonId:selectedLessonId,attempts:0,last:0};data.grammarMistakes[exercise.id]={lessonId:selectedLessonId,attempts:old.attempts+1,last:Date.now()};}save();renderLibrary();}
function nextGrammarStage(){const exercises=lessonExercises(selectedLessonId);if(lessonSession.index<exercises.length-1){lessonSession.index++;resetGrammarStage();renderLibrary();window.scrollTo(0,0);return;}data.grammarProgress[selectedLessonId]={completed:true,score:lessonSession.score,attempts:lessonSession.attempts};lessonSession.done=true;save();feedback.play('success');renderLibrary();window.scrollTo(0,0);}
function grammarExerciseBody(exercise,lesson){
 if(exercise.mode==='scene')return `<div class="scene-options">${exercise.options.map(option=>button(esc(option),'grammar-choice','choice-card',`data-value="${esc(option)}"`)).join('')}</div>`;
 if(exercise.mode==='build')return `<div class="skeleton-board"><div class="skeleton-answer">${lessonSession.chosen.length?lessonSession.chosen.map(index=>button(esc(lessonSession.pool.find(item=>item.index===index).text),'grammar-unpick','sound-block chosen',`data-index="${index}"`)).join(''):'<span>按顺序点击声音积木或句子骨架</span>'}</div><div class="skeleton-pool">${lessonSession.pool.map(item=>button(esc(item.text),'grammar-pick','sound-block',`data-index="${item.index}" ${lessonSession.chosen.includes(item.index)?'disabled':''}`)).join('')}</div></div>`;
 if(exercise.mode==='speak')return `<div class="speak-challenge"><span>只看提示，先自己说</span><h2>${esc(exercise.prompt.replace(/^.*：“?|”$/g,''))}</h2>${lesson.unitId==='phonics'?`<div class="sound-blocks">${lesson.soundBlocks.map((block,index)=>button(esc(block),'grammar-play','sound-block',`data-text="${esc(lesson.soundSamples[index])}" title="示范词：${esc(lesson.soundSamples[index])}"`)).join('')}</div>`:''}<div class="dialog-actions">${button(ic('sound')+' 听参考答案','grammar-play','small-outline',`data-text="${esc(exercise.answer)}"`)}${button('我已经开口说了','grammar-self','accent')}</div></div>`;
 return `<div class="grammar-input-wrap"><input id="grammar-answer" class="grammar-answer" value="${esc(lessonSession.input)}" placeholder="在这里输入英文" autocomplete="off" spellcheck="false" aria-label="语法练习答案">${button('检查答案','grammar-check','accent')}</div>`;
}
function grammarLessonPage(){
 const lesson=currentGrammarLesson(),unit=learningUnits.find(item=>item.id===lesson?.unitId);if(!lesson||!unit)return learningPathPage();
 if(lessonSession?.done){const related=sentences.filter(sentence=>grammarTagsForSentence(sentence).includes(lesson.id)).slice(0,3);return `${button('← 返回学习路径','grammar-back','text-button')}<section class="lesson-finish"><span>闯关完成</span><h1>${esc(lesson.title)}</h1><strong>${lessonSession.score}/6</strong><p>现在你已经能用这个结构处理真实生活表达。</p><div class="finish-sentences">${related.map(sentence=>`<article><b>${esc(sentence.en)}</b><span>${esc(sentence.zh)}</span>${button(ic('sound')+' 听一句','grammar-play','text-button',`data-text="${esc(sentence.en)}"`)}</article>`).join('')}</div><div class="dialog-actions">${related.length?button('用真实句子练口语','grammar-real','accent',`data-ids="${related.map(s=>s.id).join(',')}"`):''}${button('返回学习路径','grammar-back','small-outline')}</div></section>`;}
 const exercise=currentGrammarExercise(),stages=lessonExercises(lesson.id),progress=(lessonSession.index+1)/stages.length*100;
 return `<div class="lesson-shell"><header class="lesson-top"><div>${button('← 学习路径','grammar-back','text-button')}<span>${esc(unit.title)} · 第 ${lessonSession.index+1}/6 关</span></div><b>${esc(lessonStageLabel(exercise.mode))}</b></header><div class="lesson-progress"><i style="width:${progress}%"></i></div><main class="lesson-player"><aside class="human-rule"><span>一句人话</span><h1>${esc(lesson.title)}</h1><p>${esc(lesson.plain)}</p><div class="formula"><small>声音 / 句子骨架</small><b>${esc(lesson.formula)}</b></div>${lesson.unitId==='phonics'?`<div class="sound-blocks">${lesson.soundBlocks.map((block,index)=>button(esc(block),'grammar-play','sound-block',`data-text="${esc(lesson.soundSamples[index])}" title="示范词：${esc(lesson.soundSamples[index])}"`)).join('')}</div>`:''}<details><summary>以后会见到的名字</summary><p>${esc(lesson.focus)}</p></details></aside><section class="challenge-card"><span class="stage-name">${esc(lessonStageLabel(exercise.mode))}</span><h2>${esc(exercise.prompt)}</h2>${grammarExerciseBody(exercise,lesson)}${lessonSession.checked?`<div class="grammar-feedback ${lessonSession.correct?'good':'bad'}"><b>${lessonSession.correct?'答对了，骨架接上了':'先看懂差在哪，再继续'}</b><p>参考答案：${esc(exercise.answer)}</p><small>${esc(exercise.explanation)}</small><div>${button('下一关 →','grammar-next','accent')}</div></div>`:''}</section></main></div>`;
}
function renderLibrary(){applyTheme();const nav=[['courses','课程'],['grammar','语法闯关'],['review','错题与复习'],['favorites','收藏句子'],['vocabulary','单词本'],['stats','学习记录'],['backup','备份']];let content='';
if(page==='complete')content=`<section class="empty"><h1>本轮练习完成</h1><p>已保存所有提交记录。跳过的句子不会记为掌握。</p>${button('返回课程','nav','accent','data-page="courses"')}${button('再练一轮','restart','small-outline')}</section>`;
else if(page==='courses')content=catalogPage();
else if(page==='course')content=coursePage();
else if(page==='grammar')content=learningPathPage();
else if(page==='grammar-lesson')content=grammarLessonPage();
else if(page==='review'||page==='favorites'){const list=page==='review'?due():sentences.filter(s=>data.favorites.includes(s.id));content=`<div class="library-heading"><h1>${page==='review'?'错题与到期复习':'收藏句子'}</h1><p>${page==='review'?'答错立即加入；答对后按 1、3、7、14、30 天复习。':'把常用表达留在这里。'}</p>${list.length?button('开始集中练习','collection','accent'):''}</div>${list.length?list.map(s=>`<article class="sentence-row"><div><h3>${s.en}</h3><p>${s.zh}</p></div>${button(ic('sound'),'sentence-play','icon',`data-id="${s.id}" aria-label="朗读句子"`)}</article>`).join(''):'<div class="empty">这里暂时没有句子。</div>'}`;}
else if(page==='vocabulary')content=`<div class="library-heading"><h1>我的单词本</h1><p>点击练习页的单词可查看释义并收藏。</p><input id="word-search" placeholder="搜索内置课程词汇" aria-label="搜索单词"></div><div id="word-results">${wordList(wordFavorites.length?wordFavorites:Object.keys(dictionary))}</div>`;
else if(page==='stats'){const r=Object.values(data.records),all=r.reduce((a,x)=>a+x.attempts,0),ok=r.reduce((a,x)=>a+x.correct,0);content=`<h1>学习记录</h1><div class="stats"><div><strong>${all}</strong>练习次数</div><div><strong>${all?Math.round(ok/all*100):0}%</strong>通过 / 自评记住</div><div><strong>${Object.keys(data.daily).length}</strong>学习天数</div></div><h2>每日记录</h2>${Object.entries(data.daily).reverse().map(([day,n])=>`<p class="daily-row"><span>${day}</span><b>${n} 次</b></p>`).join('')||'<p>完成第一道练习，进步就会留在这里。</p>'}`;}
else content=`<h1>学习记录备份</h1><p>进度和设置保存在当前浏览器；录音仅在本次练习中保留。</p><div class="dialog-actions">${button('导出备份','export','accent')}<label class="small-outline file-label">导入备份<input id="import" type="file" accept=".json"></label></div><section class="model-card"><h2>声音来自你自己的模型</h2><p>Kokoro 82M：${modelInfo.tts}<br>Whisper tiny.en：${modelInfo.asr}</p><p>识别一致度是文字对齐结果，不是音素发音得分。模型音色与原站不同，未提供童声音色。</p></section>`;
$('#app').innerHTML=`<div class="library"><header><strong>初言口语 <small>PHONICS · GRAMMAR · SPEAKING</small></strong><nav>${nav.map(([p,t])=>button(t,'nav',(page===p||(p==='courses'&&page==='course')||(p==='grammar'&&page==='grammar-lesson'))?'active':'',`data-page="${p}"`)).join('')}</nav>${saved?button(ic('sound')+' 返回练习','resume','small-outline'):''}</header><main class="${page==='grammar-lesson'?'lesson-main':''}">${content}</main></div>`;}
function wordList(words){return words.map(w=>`<article class="sentence-row"><div><h3>${esc(w)} <small>/${wordInfo(w).ipa}/</small></h3><p>${wordInfo(w).meaning}</p></div>${button(ic('sound'),'word-play','icon',`data-word="${esc(w)}" aria-label="朗读 ${esc(w)}"`)}${button(ic('star'),'word-favorite','icon',`data-word="${esc(w)}" aria-label="收藏 ${esc(w)}" aria-pressed="${wordFavorites.includes(w)}"`)}</article>`).join('');}
function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify({version:2,data,settings,wordFavorites,session:saved},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='初言新版备份.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;e.preventDefault();const a=el.dataset.action;
if(a==='settings'){panel=!panel;render();}else if(a==='library'||a==='nav'){if(page==='practice')saved={...session};cleanup();page=a==='library'?'courses':el.dataset.page;panel=false;save();render();window.scrollTo(0,0);}
else if(a==='course'){const c=courses.find(c=>c.id===el.dataset.id);start(c.items.map(s=>s.id),el.dataset.mode);}
else if(a==='course-details'){selectedCourseId=el.dataset.id;page='course';renderLibrary();window.scrollTo(0,0);}
else if(a==='sentence-start'){const c=courses.find(c=>c.id===el.dataset.course);start(c.items.map(s=>s.id),'speak',Number(el.dataset.index));}
else if(a==='back-courses'){page='courses';renderLibrary();window.scrollTo(0,0);}
else if(a==='category'){catalogFilters.category=el.dataset.value;catalogLimit=18;renderLibrary();}
else if(a==='more-courses'){catalogLimit+=18;renderLibrary();}
else if(a==='resume'){const r=saved||session;start(r.ids,r.mode,r.index,r.elapsed);}else if(a==='restart')start(session.ids,session.mode);
else if(a==='collection')start((page==='review'?due():sentences.filter(s=>data.favorites.includes(s.id))).map(s=>s.id));
else if(a==='play')play();else if(a==='word-play')play(el.dataset.word);else if(a==='sentence-play'||a==='context-play'){const target=sentences.find(s=>s.id===el.dataset.id);if(target)play(target.en);}else if(a==='word')wordDialog(el.dataset.word);
else if(a==='word-favorite'){const w=el.dataset.word;wordFavorites=wordFavorites.includes(w)?wordFavorites.filter(x=>x!==w):[...wordFavorites,w];save();el.setAttribute('aria-pressed',wordFavorites.includes(w));if($('#modal'))el.textContent=wordFavorites.includes(w)?'取消单词收藏':'收藏单词';}
else if(a==='sound-preview'){feedback.play('key','a');setTimeout(()=>feedback.play('key','s'),95);setTimeout(()=>feedback.play('word'),190);}
else if(a==='grammar-start')startGrammarLesson(el.dataset.id);
else if(a==='grammar-back'){page='grammar';lessonSession=null;renderLibrary();window.scrollTo(0,0);}
else if(a==='grammar-play')play(el.dataset.text,1);
else if(a==='grammar-choice')completeGrammarAnswer(el.dataset.value);
else if(a==='grammar-pick'){const index=Number(el.dataset.index);lessonSession.chosen.push(index);feedback.play('pick');renderLibrary();if(lessonSession.chosen.length===lessonSession.pool.length){const lesson=currentGrammarLesson(),value=lessonSession.chosen.map(i=>lessonSession.pool.find(item=>item.index===i).text).join(lesson.unitId==='phonics'?'':' ');completeGrammarAnswer(value);}}
else if(a==='grammar-unpick'){lessonSession.chosen=lessonSession.chosen.filter(index=>index!==Number(el.dataset.index));feedback.play('unpick');renderLibrary();}
else if(a==='grammar-check')completeGrammarAnswer(lessonSession.input);
else if(a==='grammar-self')completeGrammarAnswer(currentGrammarExercise().answer,true);
else if(a==='grammar-next')nextGrammarStage();
else if(a==='grammar-real'){start(String(el.dataset.ids||'').split(',').filter(Boolean),'speak');}
else if(a==='export')exportData();else if(a==='confirm'){const f=dialogAction;$('#modal')?.close();f?.();}
else if(a==='shortcuts'){showDialog('自定义快捷键',`<p>以下按键与 Alt 组合使用。Enter 检查 / 下一句，空格启动 / 停止录音。</p>${Object.entries({play:'朗读',answer:'答案',favorite:'收藏',next:'下一句',previous:'上一句'}).map(([key,label])=>`<label class="shortcut-row">${label}<input data-shortcut="${key}" aria-label="${label}快捷键" value="${esc(settings.keys[key])}" readonly></label>`).join('')}<p>点击输入框后按一个按键，立即保存。</p>`);}
else if(page==='practice'){
 if(a==='pick'){q.chosen.push(Number(el.dataset.index));keySound('pick');render();if(q.chosen.length===q.pool.length)check();}
 else if(a==='unpick'){q.chosen=q.chosen.filter(i=>i!==Number(el.dataset.index));keySound('unpick');render();}
 else if(a==='undo'){q.chosen.pop();keySound('unpick');render();}else if(a==='clear'){q.chosen=[];keySound('clear');render();}
 else if(a==='check')check();else if(a==='reveal')toggleAnswer();
 else if(a==='analysis'){analysisView=analysisView==='words'?'grammar':'words';render();}
 else if(a==='retry'){reset();render();autoPlay();}else if(a==='toggle-speaking-prompt'){q.hideEnglish=!q.hideEnglish;render();}else if(a==='self-complete'){recordResult(true);q.checked=true;next(1);}else if(a==='next'||a==='learn-next')next(1);else if(a==='prev')next(-1);
 else if(a==='favorite'){const id=current().id;data.favorites=data.favorites.includes(id)?data.favorites.filter(x=>x!==id):[...data.favorites,id];save();el.setAttribute('aria-pressed',data.favorites.includes(id));}
 else if(a==='record')record();else if(a==='fullscreen'){try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen();}catch{toast('请使用浏览器菜单进入全屏。');}}
}
});
document.addEventListener('input',e=>{if(e.target.dataset.input==='word'){const index=Number(e.target.dataset.index),expected=current().en.split(' ')[index]||'';q.inputs[index]=e.target.value;if(String(e.inputType||'').includes('delete'))keySound('delete');else if(assess(e.target.value,expected)&&!q.completedWords.includes(index)){q.completedWords.push(index);keySound('word');}else keySound('key',e.data||e.target.value.slice(-1));if(!e.isComposing&&assess(q.inputs.join(' '),current().en))check();}if(e.target.id==='grammar-answer'){lessonSession.input=e.target.value;if(String(e.inputType||'').includes('delete'))keySound('delete');else keySound('key',e.data||e.target.value.slice(-1));}if(e.target.id==='word-search')$('#word-results').innerHTML=wordList(Object.keys(dictionary).filter(w=>w.includes(e.target.value.trim().toLowerCase())));if(e.target.id==='course-search'){catalogFilters.query=e.target.value;catalogLimit=18;const pos=e.target.selectionStart;renderLibrary();requestAnimationFrame(()=>{const input=$('#course-search');input?.focus();input?.setSelectionRange(pos,pos);});}});
document.addEventListener('change',async e=>{const key=e.target.dataset.setting;if(key){settings[key]=e.target.type==='checkbox'?e.target.checked:['rate','loops','successLoops','revealAt','size','soundVolume'].includes(key)?Number(e.target.value):e.target.value;save();if(key==='fragment')reset();render();if(key==='soundProfile'||key==='soundVolume')feedback.play('word');}if(e.target.dataset.catalog){catalogFilters[e.target.dataset.catalog]=e.target.value;catalogLimit=18;renderLibrary();}if(e.target.id==='mode'){const mode=e.target.value;e.target.value=session.mode;showDialog('切换练习方式',`<p>将从本课第一句开始${modes[mode]}。已提交的学习记录会保留。</p><div class="dialog-actions"><button>取消</button>${button('切换并从头开始','confirm','accent')}</div>`,()=>start(session.ids,mode));}
if(e.target.id==='import'){try{const file=e.target.files[0];if(!file||file.size>2000000)throw Error();const x=JSON.parse(await file.text());if(x.version!==2||!x.data||!x.settings)throw Error();showDialog('导入学习备份',`<p>导入将替换本机记录。请先导出当前记录。</p><div class="dialog-actions">${button('先导出','export','small-outline')}${button('确认导入','confirm','accent')}</div>`,()=>{data=restore(JSON.stringify(x.data));settings=safeSettings(x.settings,defaults);wordFavorites=Array.isArray(x.wordFavorites)?x.wordFavorites.filter(w=>typeof w==='string'&&dictionary[w]):[];saved=validSession(x.session,sentences.map(s=>s.id),Object.keys(modes))?x.session:null;save();render();toast('备份已导入');});}catch{toast('备份格式无效，请选择新版初言导出的 JSON。');}}});
document.addEventListener('keydown',e=>{if(e.target.dataset.shortcut){e.preventDefault();if(['Alt','Control','Meta','Shift','Tab'].includes(e.key))return;const key=e.target.dataset.shortcut;if(Object.entries(settings.keys).some(([k,v])=>k!==key&&v===e.key))return toast('这个按键已被使用，请换一个。');settings.keys[key]=e.key;e.target.value=e.key;save();return;}if($('#modal')||e.isComposing)return;if(page==='grammar-lesson'){if(e.target.id==='grammar-answer'&&e.key==='Enter'){e.preventDefault();completeGrammarAnswer(lessonSession.input);}return;}if(page!=='practice')return;
if(e.ctrlKey||e.metaKey){const o=$('#shortcut-overlay');if(o&&settings.shortcuts){o.hidden=false;o.textContent=`Alt + ${settings.keys.play} 朗读　 Alt + ${settings.keys.answer} 答案　 Enter 检查 / 下一句　 空格 录音`;}}
if(e.altKey){const action=Object.entries(settings.keys).find(([,key])=>key.toLowerCase()===e.key.toLowerCase())?.[0];if(action){e.preventDefault();({play:()=>play(),answer:()=>toggleAnswer(),favorite:()=>document.querySelector('[data-action="favorite"]').click(),next:()=>next(1),previous:()=>next(-1)})[action]();}return;}
if(e.target.dataset.input==='word'){const i=Number(e.target.dataset.index);if(e.key===' '){e.preventDefault();keySound('space');document.querySelector(`[data-input="word"][data-index="${i+1}"]`)?.focus();}if(e.key==='Backspace'&&!e.target.value){keySound('delete');document.querySelector(`[data-input="word"][data-index="${i-1}"]`)?.focus();}}
if(e.key==='Enter'&&!e.target.closest('button,select')){e.preventDefault();q.checked||session.mode==='learn'?next(1):check();}
if(e.code==='Space'&&!e.target.closest('input,select,button')&&(session.mode==='speak'||q.checked||q.revealed||session.mode==='learn')){e.preventDefault();record();}
if(e.key==='Escape'&&panel){panel=false;render();}});
document.addEventListener('keyup',e=>{if(e.key==='Control'||e.key==='Meta'){const o=$('#shortcut-overlay');if(o)o.hidden=true;}});
document.addEventListener('paste',e=>{if(e.target.dataset.input!=='word')return;const text=e.clipboardData.getData('text').trim();if(text.split(/\s+/).length>1){e.preventDefault();q.inputs=text.split(/\s+/);render();if(assess(text,current().en))check();}});
setInterval(()=>{if(page==='practice'&&document.visibilityState==='visible'&&!$('#modal')){session.elapsed++;if($('#timer'))$('#timer').textContent=fmt(session.elapsed);if(session.elapsed%5===0){saved={...session};save();}}},1000);
window.addEventListener('pagehide',()=>{if(page==='practice')saved={...session};save();cleanup();});
async function status(){try{modelInfo=await (await fetch('/api/status')).json();}catch{modelInfo={tts:'服务未连接',asr:'服务未连接'};}const target=document.querySelector('.settings-popover .model-card p');if(target)target.innerHTML=`Kokoro 82M · ${esc(modelInfo.tts)}<br>Whisper tiny.en · ${esc(modelInfo.asr)}`;if(modelInfo.tts!=='就绪'||modelInfo.asr!=='就绪')setTimeout(status,5000);}
reset();render();draw();status();
