// 初言原创自然拼读与口语语法课程。说明、例句和练习均为独立编写。
const phonicsLessons=[
 {title:'字母名和字母音不是一回事',focus:'字母音',plain:'字母有“名字”，也有放进单词里真正发出的“声音”。先听声音，不用汉字硬凑。',formula:'字母名 ≠ 字母音',blocks:['a /æ/','b /b/','m /m/','s /s/'],samples:['apple','book','map','sun'],words:[['map','地图'],['bag','包'],['Sam','萨姆']],distractors:['red','sit'],sentence:['This is my bag.','这是我的包。']},
 {title:'五个短元音',focus:'短元音',plain:'嘴巴短短地发一下，不拖长：a、e、i、o、u 是单词中间最常见的声音发动机。',formula:'a /æ/ · e /e/ · i /ɪ/ · o /ɒ/ · u /ʌ/',blocks:['a /æ/','e /e/','i /ɪ/','o /ɒ/','u /ʌ/'],samples:['cat','bed','sit','hot','cup'],words:[['cat','猫'],['bed','床'],['sit','坐']],distractors:['bike','home'],sentence:['The cat is on the bed.','猫在床上。']},
 {title:'常见辅音一口气',focus:'辅音',plain:'辅音像单词的外壳。发音时别偷偷加“呃”，b 是 /b/，不要读成“波”。',formula:'声音要短：/b/ /k/ /d/ /f/ /g/',blocks:['b /b/','c /k/','d /d/','f /f/','g /g/'],samples:['bag','cat','dog','fish','go'],words:[['bag','包'],['dog','狗'],['fish','鱼']],distractors:['map','fish'],sentence:['The dog has a bag.','这只狗有一个包。']},
 {title:'CVC 三块一滑就读',focus:'CVC 拼读',plain:'辅音、短元音、辅音排成三块。慢慢连，再一口滑过去：c-a-t，cat。',formula:'辅音 + 短元音 + 辅音',blocks:['c /k/','a /æ/','t /t/'],samples:['cat','apple','top'],words:[['cat','猫'],['map','地图'],['sit','坐']],distractors:['sit','dog'],sentence:['A cat can sit.','一只猫会坐。']},
 {title:'开头两个辅音都要听见',focus:'辅音连缀',plain:'两个辅音站一起时谁也不消失。stop 里的 s 和 t 都要发出来。',formula:'st · sp · bl · gr · tr',blocks:['s+t /st/','b+l /bl/','g+r /gr/','t+r /tr/'],samples:['stop','blue','green','train'],words:[['stop','停'],['blue','蓝色'],['train','火车']],distractors:['blue','train'],sentence:['The blue train can stop.','蓝色火车能停下。']},
 {title:'静音 e 让元音说名字',focus:'长元音与静音 e',plain:'词尾 e 常常不出声，却会让前面的元音变成长音，像给它按下“名字模式”。',formula:'a_e /eɪ/ · i_e /aɪ/ · o_e /əʊ/',blocks:['a_e /eɪ/','i_e /aɪ/','o_e /əʊ/'],samples:['name','bike','home'],words:[['name','名字'],['bike','自行车'],['home','家']],distractors:['sit','hot'],sentence:['I ride my bike home.','我骑自行车回家。']},
 {title:'两个元音结伴发一个主音',focus:'元音组合',plain:'有些元音组合常一起工作。先认整个声音积木，不要一个字母一个字母硬念。',formula:'ee /iː/ · ai /eɪ/ · oa /əʊ/ · oo /uː/ 或 /ʊ/',blocks:['ee /iː/','ai /eɪ/','oa /əʊ/','oo /uː/'],samples:['see','rain','boat','food'],words:[['see','看见'],['rain','雨'],['boat','船']],distractors:['cat','hot'],sentence:['I can see the boat.','我能看见那条船。']},
 {title:'sh ch th 是固定搭档',focus:'辅音组合',plain:'两个字母会组成一个新声音。看到 sh、ch、th，先把它们当成一块。',formula:'sh /ʃ/ · ch /tʃ/ · th /θ/ 或 /ð/',blocks:['sh /ʃ/','ch /tʃ/','th /θ/','th /ð/'],samples:['shop','chair','think','this'],words:[['shop','商店'],['chair','椅子'],['this','这个']],distractors:['map','dog'],sentence:['This chair is in the shop.','这把椅子在商店里。']},
 {title:'长单词先切音节',focus:'音节拆分',plain:'长单词不用一口吞。看元音核心，把单词切成两三拍再合起来。',formula:'ta-ble · ho-tel · to-ma-to',blocks:['ta + ble','ho + tel','to + ma + to'],samples:['table','hotel','tomato'],words:[['table','桌子'],['hotel','酒店'],['tomato','西红柿']],distractors:['cat','train'],sentence:['The tomato is on the table.','西红柿在桌子上。']},
 {title:'重读的一拍更响更清楚',focus:'音节与重音',plain:'多音节词里总有一拍更有力。抓住重读，其他音节自然放轻，整词就顺了。',formula:'TA-ble · ho-TEL · ba-NA-na',blocks:['TA-ble','ho-TEL','ba-NA-na'],samples:['table','hotel','banana'],words:[['table','桌子'],['hotel','酒店'],['banana','香蕉']],distractors:['hotel','banana'],sentence:['I left a banana at the hotel.','我把一根香蕉落在酒店了。']}
];

const grammarUnits=[
 {id:'g01',title:'先搭句子骨架',subtitle:'把中文想法装进英语顺序',level:'入门',lessons:[
  ['谁先站出来','英语句子通常先说“谁”，再说发生什么。','谁 + 动作','基本词序'],
  ['动作后面接对象','做什么之后，直接说明动作落在谁或什么上。','谁 + 动作 + 对象','主谓宾'],
  ['地点时间往后挂','先把核心说完，再把地点和时间挂到句尾。','骨架 + 地点 + 时间','状语位置'],
  ['形容状态用 be','没有动作，只是在说身份、状态或位置，就用 be 把两边连起来。','谁 + be + 状态','主系表'],
  ['一句只抓一个主干','长句先找谁和动作，其他信息都是挂件。','主干 + 挂件','句子主干']
 ],examples:[['我每天做早餐。','I make breakfast every day.'],['她喜欢这家咖啡馆。','She likes this cafe.'],['我们晚上在家吃饭。','We eat at home in the evening.'],['这家店很安静。','The shop is quiet.'],['我的朋友在车站等我。','My friend waits for me at the station.']],mistakes:[['Make I breakfast.','I make breakfast.','中文可以省主语，英语通常要先把“谁”说出来。'],['She this cafe likes.','She likes this cafe.','对象通常跟在动作后面。'],['In the evening we at home eat.','We eat at home in the evening.','先说核心，再补地点和时间。'],['The shop very quiet.','The shop is very quiet.','状态句需要 be 来连接。'],['My friend at the station me waits.','My friend waits for me at the station.','先抓主干，再挂地点。']]},
 {id:'g02',title:'be 动词变形术',subtitle:'介绍身份、状态和位置',level:'入门',lessons:[
  ['I 后面认准 am','说“我是……”时，I 和 am 是固定搭档。','I am','be 动词'],['你我之外分 is 和 are','一个人或物用 is，复数和 you 用 are。','he/she/it is · you/we/they are','be 动词'],['不是这样怎么说','在 am、is、are 后面直接加 not。','be + not','be 否定'],['把 be 提到前面问','想问“是不是”，把 am、is、are 搬到句首。','Be + 谁 + …?','be 疑问'],['地点也靠 be 连接','人在或东西在什么地方，仍然用 be 连接。','谁/什么 + be + 地点','存在位置']
 ],examples:[['我是新来的。','I am new here.'],['她今天很忙。','She is busy today.'],['我们现在不饿。','We are not hungry now.'],['你准备好了吗？','Are you ready?'],['钥匙在桌上。','The key is on the table.']],mistakes:[['I is new here.','I am new here.','I 只和 am 搭配。'],['They is busy.','They are busy.','复数主语用 are。'],['We not are hungry.','We are not hungry.','not 放在 be 后面。'],['You are ready?','Are you ready?','标准一般疑问句把 be 放到句首。'],['The key on the table.','The key is on the table.','位置句不能漏掉 be。']]},
 {id:'g03',title:'每天做什么',subtitle:'用一般现在时说习惯和事实',level:'入门',lessons:[
  ['习惯动作直接说','I、you、we、they 后面直接用动作原形。','谁 + 动词原形','一般现在时'],['他她它动作加 s','一个“他/她/它”做日常动作，动词通常加 s。','he/she/it + 动词-s','第三人称单数'],['不做用 do not','否定时让 do 来扛 not，后面的动作恢复原形。','do/does not + 动词原形','一般现在时否定'],['问习惯让 do 先出场','一般动作句提问，用 Do 或 Does 开头。','Do/Does + 谁 + 动词原形?','一般现在时疑问'],['频率放在动作前','always、usually、often 常放在主要动作前，be 后。','频率词 + 动作','频率副词']
 ],examples:[['我每天步行上班。','I walk to work every day.'],['他早上喝咖啡。','He drinks coffee in the morning.'],['我周日不工作。','I do not work on Sundays.'],['她住在附近吗？','Does she live nearby?'],['我们通常在家做饭。','We usually cook at home.']],mistakes:[['I walks to work.','I walk to work.','I 后面的日常动作不用加 s。'],['He drink coffee.','He drinks coffee.','he 后面的动作通常加 s。'],['I do not works on Sundays.','I do not work on Sundays.','do 已经变形，后面用动词原形。'],['Does she lives nearby?','Does she live nearby?','does 后面恢复动词原形。'],['We cook usually at home.','We usually cook at home.','频率词通常放在主要动作前。']]},
 {id:'g04',title:'会问才会聊',subtitle:'把不知道的信息问出来',level:'基础',lessons:[
  ['是不是先看句子发动机','be 句把 be 提前，动作句请 do 帮忙。','Be…? / Do…?','一般疑问句'],['问什么就把问词放前面','who、what、where、when、why、how 放在问句最前。','问词 + 一般问句','特殊疑问句'],['二选一用 or','把两个选项放在同一个问句里，用 or 连接。','A or B?','选择问句'],['多少和多长要成组','how much、how many、how long 都要当成一个问词块。','how + 范围词','how 词组'],['确认一下用短尾巴','先说判断，再用一个很短的问句请对方确认。','陈述句 + 确认尾巴','附加确认']
 ],examples:[['你累了吗？','Are you tired?'],['洗手间在哪里？','Where is the restroom?'],['你想要茶还是咖啡？','Do you want tea or coffee?'],['到那里要多久？','How long does it take?'],['我们八点见，好吗？','We meet at eight, right?']],mistakes:[['Do you are tired?','Are you tired?','be 自己就能提问，不需要 do。'],['The restroom is where?','Where is the restroom?','问词通常放句首。'],['Do you want tea and coffee?','Do you want tea or coffee?','二选一用 or。'],['How time does it take?','How long does it take?','询问时长用 how long。'],['We meet at eight, yes?','We meet at eight, right?','日常确认常用 right。']]},
 {id:'g05',title:'把故事放到过去',subtitle:'说昨天、刚才和从前',level:'基础',lessons:[
  ['过去动作换过去式','时间已经结束，动作词换成过去式。','谁 + 动词过去式','一般过去时'],['过去否定交给 did not','did 已经表示过去，后面动作恢复原形。','did not + 动词原形','过去否定'],['过去提问让 did 开头','问过去发生的动作，用 Did 带头。','Did + 谁 + 动词原形?','过去疑问'],['当时正在做用 was doing','说过去某一刻正在进行的动作，用 was/were 加 doing。','was/were + doing','过去进行时'],['过去常常用 used to','以前经常如此、现在不同，可以用 used to。','used to + 动词原形','used to']
 ],examples:[['我昨天给妈妈打了电话。','I called my mom yesterday.'],['我昨晚没有做饭。','I did not cook last night.'],['你看到我的消息了吗？','Did you see my message?'],['你打来时我正在开车。','I was driving when you called.'],['我以前住在这里。','I used to live here.']],mistakes:[['I call my mom yesterday.','I called my mom yesterday.','结束的过去时间需要过去式。'],['I did not cooked last night.','I did not cook last night.','did 后面用原形。'],['Did you saw my message?','Did you see my message?','did 已经承担过去，动作恢复原形。'],['I driving when you called.','I was driving when you called.','进行时不能漏掉 was。'],['I use to live here.','I used to live here.','肯定句写 used to。']]},
 {id:'g06',title:'把计划放到未来',subtitle:'预测、决定和已经安排好的事',level:'基础',lessons:[
  ['临时决定用 will','刚刚决定或作出承诺时，will 很顺手。','will + 动词原形','will'],['有迹象的打算用 going to','已经有打算或眼前有证据，用 be going to。','be going to + 动词','be going to'],['日程安排用进行时','已经约好的见面和行程，可用现在进行时说未来。','be doing + 未来时间','进行时表将来'],['未来否定在 will 后加 not','will not 或 won’t 后面继续用动词原形。','will not + 动词原形','未来否定'],['问计划先问什么时候','用 when、what time、how 等问具体安排。','问词 + will/be…','未来疑问']
 ],examples:[['我来帮你。','I will help you.'],['我们打算今晚点餐。','We are going to order food tonight.'],['我明天下午见医生。','I am seeing the doctor tomorrow afternoon.'],['我不会迟到。','I will not be late.'],['你什么时候回来？','When will you come back?']],mistakes:[['I will to help you.','I will help you.','will 后直接接动词原形。'],['We going to order food.','We are going to order food.','going to 前不能漏 be。'],['I see the doctor tomorrow afternoon.','I am seeing the doctor tomorrow afternoon.','已安排事项可用现在进行时。'],['I will not late.','I will not be late.','late 是状态，前面需要 be。'],['When you will come back?','When will you come back?','问句中 will 放在主语前。']]},
 {id:'g07',title:'动作进行到哪一步',subtitle:'正在发生、已经完成和持续至今',level:'进阶',lessons:[
  ['眼前正在发生用 doing','说此刻正在做，用 be 加动作-ing。','be + doing','现在进行时'],['已经发生且影响现在','不强调具体过去时间，只强调现在结果，用 have done。','have/has + 过去分词','现在完成时'],['从过去持续到现在','配合 for 或 since 表示持续了多久。','have done + for/since','持续'],['去过和去了要分清','have been 表示去过并回来；have gone 表示已经去了。','have been / have gone','been 与 gone'],['有具体过去时间就用过去式','出现 yesterday、last year 等结束时间，不用现在完成时。','过去式 + 结束时间','完成时与过去时']
 ],examples:[['我正在等公交车。','I am waiting for the bus.'],['我已经订好房间了。','I have booked the room.'],['我在这里住了三年。','I have lived here for three years.'],['她去过上海两次。','She has been to Shanghai twice.'],['我昨天买了这件外套。','I bought this coat yesterday.']],mistakes:[['I waiting for the bus.','I am waiting for the bus.','进行时需要 be。'],['I have book the room.','I have booked the room.','have 后用过去分词。'],['I live here since three years.','I have lived here for three years.','一段时间用 for，并用完成时。'],['She has gone to Shanghai twice.','She has been to Shanghai twice.','说经历用 has been。'],['I have bought this coat yesterday.','I bought this coat yesterday.','具体结束时间搭配一般过去时。']]},
 {id:'g08',title:'东西有多少',subtitle:'名词、数量和所属关系',level:'基础',lessons:[
  ['一个还是多个','可数名词超过一个时通常变复数。','one + 单数 · two + 复数','名词复数'],['水和信息不能直接数','不可数名词要借助 some 或容器量词。','some + 不可数名词','不可数名词'],['几个用 many 多少量用 much','可数复数问 how many，不可数问 how much。','many + 复数 · much + 不可数','数量提问'],['一杯一片帮你数','用 a cup of、a piece of 把不可数东西变成可数份。','单位 + of + 名词','量词'],['谁的东西加所有格','人名或名词后加 ’s，表示属于谁。','人 + ’s + 东西','所有格']
 ],examples:[['我需要两张票。','I need two tickets.'],['请给我一些水。','Please give me some water.'],['你有多少个袋子？','How many bags do you have?'],['我要一杯茶。','I would like a cup of tea.'],['这是我姐姐的车。','This is my sister’s car.']],mistakes:[['I need two ticket.','I need two tickets.','two 后面的可数名词用复数。'],['Please give me a water.','Please give me some water.','water 通常不可数。'],['How much bags do you have?','How many bags do you have?','bags 可数，用 how many。'],['I want a tea cup of.','I want a cup of tea.','量词结构按“单位 + of + 东西”。'],['This is my sister car.','This is my sister’s car.','所属关系需要 ’s。']]},
 {id:'g09',title:'这个东西说清楚了吗',subtitle:'冠词和限定词让名词有范围',level:'基础',lessons:[
  ['第一次提到一个用 a','听者还不知道是哪一个时，可数单数前用 a/an。','a/an + 可数单数','不定冠词'],['双方都知道用 the','已经提过或现场唯一、双方都明白时用 the。','the + 明确对象','定冠词'],['泛指有时不用冠词','复数或不可数名词表示一类事物时常用零冠词。','复数/不可数泛指','零冠词'],['近处 this 远处 that','单数用 this/that，复数用 these/those。','this/that · these/those','指示限定词'],['肯定 some 问否常 any','some 常用于肯定，any 常用于疑问和否定。','some / any + 名词','some 与 any']
 ],examples:[['我想买一把伞。','I want to buy an umbrella.'],['请把门关上。','Please close the door.'],['我喜欢咖啡。','I like coffee.'],['那些鞋多少钱？','How much are those shoes?'],['你有零钱吗？','Do you have any change?']],mistakes:[['I want to buy umbrella.','I want to buy an umbrella.','可数单数前需要限定。'],['Please close a door.','Please close the door.','现场明确的门用 the。'],['I like the coffee in general.','I like coffee in general.','泛指咖啡通常不用 the。'],['How much is those shoes?','How much are those shoes?','those shoes 是复数，用 are。'],['Do you have some change?','Do you have any change?','普通疑问中常用 any。']]},
 {id:'g10',title:'别重复名字',subtitle:'用代词让对话更自然',level:'基础',lessons:[
  ['谁做事用主格','I、you、he、she、we、they 放在动作前。','主格 + 动作','人称代词'],['动作落到谁用宾格','me、him、her、us、them 放在动词或介词后。','动作/介词 + 宾格','宾格'],['我的和你的有两套','my 后面带名词，mine 可以单独站。','my + 名词 · mine','物主代词'],['自己做给自己','动作回到主语自身时用 myself、yourself 等。','主语 + 动作 + 反身代词','反身代词'],['有人任何人没人','someone、anyone、no one 能代替不确定的人。','some/any/no + one','不定代词']
 ],examples:[['她每天给我发消息。','She messages me every day.'],['请和他谈谈。','Please talk to him.'],['这个座位是我的。','This seat is mine.'],['我自己修好了。','I fixed it myself.'],['有人在门口。','Someone is at the door.']],mistakes:[['Her messages I every day.','She messages me every day.','动作前用主格，动作后用宾格。'],['Please talk to he.','Please talk to him.','介词后用宾格。'],['This seat is my.','This seat is mine.','不带名词时用 mine。'],['I fixed it me.','I fixed it myself.','强调自己完成用反身代词。'],['Anyone is at the door.','Someone is at the door.','肯定句表示某人常用 someone。']]},
 {id:'g11',title:'把感觉说具体',subtitle:'描述方式、程度和比较',level:'基础',lessons:[
  ['形容词描述人和物','形容词放在 be 后或名词前。','be + 形容词 · 形容词 + 名词','形容词'],['副词描述怎么做','很多副词用 -ly，说明动作发生的方式。','动作 + 副词','副词'],['两者比较加 than','短词常加 -er，长词常用 more。','比较级 + than','比较级'],['一群里面找最强','用 the 加最高级，表示范围内最突出。','the + 最高级','最高级'],['太、很、够用不同程度词','too 表示过头，very 只是很，enough 表示够。','too/very + 形容词 · 形容词 + enough','程度']
 ],examples:[['这个房间很干净。','This room is clean.'],['请说慢一点。','Please speak slowly.'],['这家店比那家便宜。','This shop is cheaper than that one.'],['这是附近最好的咖啡馆。','This is the best cafe nearby.'],['这个箱子太重了。','This box is too heavy.']],mistakes:[['This is a cleanly room.','This is a clean room.','修饰名词用形容词 clean。'],['Please speak slow.','Please speak slowly.','说明怎么说，用副词 slowly。'],['This shop is more cheaper.','This shop is cheaper.','比较级不要重复使用 more。'],['This is best cafe nearby.','This is the best cafe nearby.','最高级前通常用 the。'],['This box is enough heavy.','This box is heavy enough.','enough 放在形容词后。']]},
 {id:'g12',title:'时间地点放对格子',subtitle:'用核心介词说明关系',level:'基础',lessons:[
  ['钟点用 at 日期用 on','具体时刻用 at，日期和星期用 on，较长时期用 in。','at 时间点 · on 日 · in 月年','时间介词'],['点、面、空间分 at on in','地点点位用 at，表面用 on，空间内部用 in。','at · on · in','地点介词'],['去向用 to 来源用 from','移动到哪里用 to，从哪里来用 from。','from A to B','方向介词'],['旁边对面之间','next to、across from、between 把相对位置说清楚。','位置词组','方位'],['一段时间用 for 起点用 since','for 后接时长，since 后接开始点。','for + 时长 · since + 起点','时间跨度']
 ],examples:[['我们七点见。','We meet at seven.'],['手机在包里。','The phone is in the bag.'],['我从机场去酒店。','I go from the airport to the hotel.'],['银行在超市对面。','The bank is across from the supermarket.'],['我在这里等了十分钟。','I have waited here for ten minutes.']],mistakes:[['We meet on seven.','We meet at seven.','具体钟点用 at。'],['The phone is on the bag.','The phone is in the bag.','包的内部用 in。'],['I go the airport to the hotel.','I go from the airport to the hotel.','来源前用 from。'],['The bank is across the supermarket.','The bank is across from the supermarket.','“在……对面”用 across from。'],['I have waited here since ten minutes.','I have waited here for ten minutes.','一段时长用 for。']]},
 {id:'g13',title:'说能力也说态度',subtitle:'情态动词让请求和判断更自然',level:'基础',lessons:[
  ['能不能用 can','能力、许可和普通请求都能用 can。','can + 动词原形','can'],['更客气用 could','could you 比 can you 更委婉，适合请陌生人帮忙。','Could you + 动词?','could'],['可能性分强弱','may 和 might 表示可能，might 通常更不确定。','may/might + 动词','可能性'],['必须和不得','must 表示强要求，must not 表示禁止。','must / must not + 动词','must'],['建议和客观需要','should 给建议，have to 表示现实要求。','should / have to + 动词','建议与义务']
 ],examples:[['我会说一点英语。','I can speak a little English.'],['您能再说一遍吗？','Could you say that again?'],['今晚可能会下雨。','It might rain tonight.'],['你必须系安全带。','You must wear a seat belt.'],['你应该早点休息。','You should rest early.']],mistakes:[['I can to speak English.','I can speak English.','can 后直接用动词原形。'],['Could you said that again?','Could you say that again?','could 后用原形。'],['It might rains tonight.','It might rain tonight.','情态动词后用原形。'],['You must to wear a seat belt.','You must wear a seat belt.','must 后不加 to。'],['You should to rest early.','You should rest early.','should 后直接用原形。']]},
 {id:'g14',title:'动作后面怎么接',subtitle:'掌握常见动词搭配和短语动作',level:'进阶',lessons:[
  ['想做计划做用 to','want、need、plan 后常接 to do。','动词 + to do','不定式'],['喜欢做继续做用 doing','enjoy、finish、keep 后常接 doing。','动词 + doing','动名词'],['让别人做不要加 to','make、let 后接人和动词原形。','make/let + 人 + 动词','使役'],['看见听见动作状态','see/hear 后可接人加 do 或 doing。','感官 + 人 + do/doing','感官动词'],['短语动词整块记用途','turn on、pick up 等要按场景当成一个动作。','动词 + 小词','短语动词']
 ],examples:[['我想预订一个房间。','I want to book a room.'],['我喜欢在周末做饭。','I enjoy cooking on weekends.'],['请让我解释。','Please let me explain.'],['我听见有人在敲门。','I heard someone knocking at the door.'],['请把音乐关小一点。','Please turn down the music.']],mistakes:[['I want booking a room.','I want to book a room.','want 后通常接 to do。'],['I enjoy to cook on weekends.','I enjoy cooking on weekends.','enjoy 后接 doing。'],['Please let me to explain.','Please let me explain.','let 后不加 to。'],['I heard someone to knock.','I heard someone knocking.','听到动作正在发生可用 doing。'],['Please turn the music down it.','Please turn it down.','代词放在短语动词中间。']]},
 {id:'g15',title:'把两句话接起来',subtitle:'条件、被动和从句骨架',level:'进阶',lessons:[
  ['如果发生就会怎样','真实可能条件常用 if + 现在时，主句用 will。','If + 现在时, will + 动词','条件句'],['不知道谁做就说结果','关注动作承受者时，用 be 加过去分词。','be + 过去分词','被动语态'],['哪个人哪样东西用 who that','在名词后用 who/that 补充说明。','名词 + who/that + 句子','定语从句'],['把一句话装进动词后','think、know、hope 后可以接完整想法。','动词 + that/疑问词 + 句子','宾语从句'],['时间原因让步用连接词','when、because、although 说明两件事的关系。','连接词 + 小句','状语从句']
 ],examples:[['如果下雨，我会坐地铁。','If it rains, I will take the subway.'],['房间每天打扫。','The room is cleaned every day.'],['帮助我的那位女士很友好。','The woman who helped me was friendly.'],['我不知道公交车什么时候来。','I do not know when the bus comes.'],['虽然很晚，但这家店还开着。','Although it is late, the shop is still open.']],mistakes:[['If it will rain, I will take the subway.','If it rains, I will take the subway.','真实条件的 if 从句通常用现在时。'],['The room cleans every day.','The room is cleaned every day.','房间是被打扫，需要被动。'],['The woman which helped me was friendly.','The woman who helped me was friendly.','指人常用 who。'],['I do not know when does the bus come.','I do not know when the bus comes.','宾语从句用陈述语序。'],['Although it is late, but the shop is open.','Although it is late, the shop is open.','although 和 but 不重复使用。']]},
 {id:'g16',title:'真实口语不端着',subtitle:'短回答、软化语气和自然衔接',level:'进阶',lessons:[
  ['能短答就别重复整句','Yes, I do 和 No, I’m not 能快速回应并保持语法完整。','Yes/No + 主语 + 助动词','短回答'],['用 right 确认信息','陈述后加 right，请对方快速确认。','陈述句, right?','附加确认'],['I think 和 maybe 给语气留余地','先加观点或可能，让判断听起来没那么硬。','I think / Maybe + 句子','语气软化'],['请求前加铺垫','Excuse me、Could you、Would you mind 能让请求自然。','铺垫 + 请求','委婉请求'],['省略重复但不丢意思','上下文清楚时，可用 one、so、too、either 避免重复。','替代词 + 上下文','口语省略']
 ],examples:[['你喜欢吗？喜欢。','Do you like it? Yes, I do.'],['你住在附近，对吧？','You live nearby, right?'],['我觉得我们应该先打电话。','I think we should call first.'],['不好意思，您能帮我吗？','Excuse me, could you help me?'],['我要小号的那个。','I will take the small one.']],mistakes:[['Do you like it? Yes, I like.','Do you like it? Yes, I do.','短回答复用问句里的助动词。'],['You live nearby, yes?','You live nearby, right?','日常确认用 right 更自然。'],['We should call first maybe I think.','I think we should call first.','软化词放在整句前更清楚。'],['Help me, please you can?','Could you help me, please?','用 could you 构成礼貌请求。'],['I will take the small.','I will take the small one.','形容词后用 one 代替名词。']]}
];

const phonicsUnit={id:'phonics',order:1,title:'自然拼读从零开始',subtitle:'听声音、拼单词，再把词放进生活短句',kind:'phonics',level:'启蒙',lessonCount:10};
export const learningUnits=[phonicsUnit,...grammarUnits.map((unit,index)=>({id:unit.id,order:index+2,title:unit.title,subtitle:unit.subtitle,kind:'grammar',level:unit.level,lessonCount:5}))];

const phonics=phonicsLessons.map((row,index)=>({
 id:`phonics-${String(index+1).padStart(2,'0')}`,unitId:'phonics',order:index+1,title:row.title,level:'启蒙',focus:row.focus,plain:row.plain,formula:row.formula,scene:'从听音到拼词',soundBlocks:row.blocks,
 examples:[...row.words.map(([en,zh])=>({en,zh})),{en:row.sentence[0],zh:row.sentence[1]}],soundSamples:row.samples,mistake:{wrong:row.words[0][0].split('').join(' - '),correct:row.words[0][0],why:'把声音积木连续滑读，最后合成一个完整单词。'}
}));

const grammar=grammarUnits.flatMap((unit,unitIndex)=>unit.lessons.map((row,index)=>{
 const examples=[0,1,2].map(step=>{const [zh,en]=unit.examples[(index+step)%unit.examples.length];return {en,zh};});
 const [wrong,correct,why]=unit.mistakes[index];
 return {id:`${unit.id}-${String(index+1).padStart(2,'0')}`,unitId:unit.id,order:11+unitIndex*5+index,title:row[0],level:unit.level,plain:row[1],formula:row[2],focus:row[3],scene:unit.subtitle,examples,mistake:{wrong,correct,why}};
}));

export const learningLessons=[...phonics,...grammar];

function makeExercises(lesson){
 const [a,b,c]=lesson.examples;
 const phonicsLesson=lesson.unitId==='phonics';
 const source=phonicsLessons.find(row=>row.title===lesson.title),distractors=source?.distractors||[];
 const distractor=phonicsLesson?distractors[0]:lesson.mistake.wrong;
 return [
  {mode:'scene',prompt:phonicsLesson?`听读目标音块，选出包含“${lesson.soundBlocks[0]}”的词。`:`在“${lesson.scene}”中，要表达“${a.zh}”，选哪句？`,options:phonicsLesson?[a.en,distractor,distractors[1]]:[a.en,distractor,b.en],answer:a.en,explanation:lesson.plain},
  {mode:'build',prompt:phonicsLesson?`把声音积木合成单词：${a.zh}`:`按英语骨架拼出：“${a.zh}”`,tokens:(phonicsLesson?a.en.split(''):a.en.split(/\s+/)).filter(Boolean),answer:a.en,explanation:lesson.formula},
  {mode:'transform',prompt:phonicsLesson?`换一个声音积木，拼出：“${b.zh}”`:`沿用同一骨架，变成：“${b.zh}”`,answer:b.en,explanation:lesson.formula},
  {mode:'fix',prompt:phonicsLesson?`把断开的声音连成一个词：${lesson.mistake.wrong}`:`找茬并改正：${lesson.mistake.wrong}`,answer:lesson.mistake.correct,explanation:lesson.mistake.why},
  {mode:'translate',prompt:phonicsLesson?`看意思拼单词：“${c.zh}”`:`中文秒转英文：“${c.zh}”`,answer:c.en,explanation:lesson.plain},
  {mode:'speak',prompt:phonicsLesson?`先滑读关键词，再说短句：“${lesson.examples.at(-1).zh}”`:`只看中文开口说：“${a.zh}”`,answer:phonicsLesson?lesson.examples.at(-1).en:a.en,explanation:'先抓用途和骨架，再完整开口。'}
 ].map((exercise,index)=>({...exercise,id:`${lesson.id}-x${index+1}`,lessonId:lesson.id,order:index+1}));
}

export const learningExercises=learningLessons.flatMap(makeExercises);
